- id: message-shorthand
  name: Commit Message Shorthand
  description: Allows the use short aliases in commit message which are rephrased by long common phrases, such as Coauthor information.
  entry: message_shorthand
  language: python
  always_run: true
  stages: [commit-msg]

- id: commit_output_for_test
  name: Test Output Hook
  description: Creates some output on pre-commit for sanity testing
  entry: message_shorthand
  language: python
  always_run: true
  stages: [pre-commit]
